name: product_explorer
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  
  # Network & API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Connectivity Check
  connectivity_plus: ^5.0.2
  
  # State Management
  provider: ^6.1.1
  
  # Caching
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Utilities
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1


flutter:


  uses-material-design: true


  # Custom fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_Bold.ttf
          weight: 700
